# Generated by Django 3.2.8 on 2022-04-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=80)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vehiculo', models.IntegerField(default=1)),
                ('conductor', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.IntegerField(default=2022)),
                ('marca', models.CharField(max_length=30)),
                ('capacidad', models.IntegerField(default=1)),
                ('usuario', models.IntegerField(default=1)),
                ('conductor', models.IntegerField(default=1)),
            ],
        ),
    ]
